spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_zdrc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    activiti:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dev_zdrc?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
      username: root
      password: root
      activiti:
        check-process-definitions: false
        database-schema-update: true  //设置自动建表
        security:
          basic:
            enabled: false
        tomcat:
          initial-size: 5
          min-idle: 5
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          filters: stat,wall,log4j
          connection-properties:
            druid.stat.merge-sql: true
            druid.stat.slow-sql-millis: 5000
          use-global-data-source-stat: true

    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  resources:
    static-locations:

shiro:
  # AES密码加密私钥(Base64加密)
  encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
  # JWT认证加密私钥(Base64加密)
  encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
  # AccessToken过期时间-5分钟-5*60(秒为单位)
  accessTokenExpireTime: 3600
  # RefreshToken过期时间-60分钟-30*60(秒为单位)
  refreshTokenExpireTime: 86400
  # Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
  shiroCacheExpireTime: 3600
  # 是否需要开启任何请求必须登录才可访问,开发时候可以为false,生产与测试必须为true
  mustLoginFlag: false
  #shiro排除过滤url,多个用,分割
  excludeUrl: bmbs/a/in,/work-flow-task/report-apply,/task/update


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_null
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
fileconf:
  #  fileUploadPath: /home/web/item-web/fileUpload/
  #  backHost: http://183.129.166.58:8080/fileUpload/
  fileUploadPath: F:\file\fileUpload
  backHost: http://127.0.0.1:8094/fileUpload/
  userFilesPath: D:/workCatalog/idea_sx_bid_flow/target/classes/userfiles/

#短信相关配置
smsconf:
  serverCode: Pks6HiB3 #* 接入代码
  serverPwd: 55IXgKpp #* 接入代码
  srcNum: 3229 #* 接入短号
  smsUrl: http://sms.zjzwfw.gov.cn/servlet/smsapi #*  接口地址
  destTypeMobile: 0     #* 目标码号类型 默认是 0:对方接收手机号码
  ON-OFF_SWITCH: on

# 万事通短信配置
wst:
  smsconf:
    url: http://39.108.85.117:6068/sms.aspx
    action: send
    userid: 25
    account: "衢州市行政服务中心"
    password: 123456
    checkcontent: 1
    on_off: "on"
#OSS
ossInfo:
  #默认使用的oss，事项配置优先级最高
  default:
  oss_qz:
    endpoint: http://oss-cn-qz-qzyzx-dt01-a.qzyzx.com
    accessKeyId:  gvgxcxGGQlBffKQb
    accessKeySecret:  pcNzSVdInxppNXqpgQ2BkXoLNiAnI8
    bucketName: zw-data-api
  oss_nw:
    endpoint: http://oss-cn-hangzhou-zjzwy01-d01-a.cloud-inner.zj.gov.cn
    accessKeyId:  WszqxjXfr3bmW6xC
    accessKeySecret:  eJAF2EqZco5uYD1Bz5fED86Vo9FRJw
    bucketName: oss-nanwei
  oss_zzlb:
    endpoint: http://59.202.42.251
    accessKeyId: d0ShTO2LveC5uDz7
    accessKeySecret: Crq4U7zlBgvfgxWOHOVs6z0jVXecVI
    bucketName: zzlbptoss

#白名单
file:
  whitelist: 183.129.166.58:8080,183.129.166.58:8005,59.202.42.251

#单点登录跳转地址
sso:
  redirect: http://192.168.31.152:8080/#/ServiceCenter_list?token=
#钉钉appkey和appsecret
ding:
  appKey: dingko3f3tm1kpi2ijpu
  appsecret: WA9zSAgDs_oRVe3_lM8MKpvDfm8YgEMv00vTJI35t72dxQKDVh9o5m3VdBmwx1av


spxt:
  interFaceFlag: http://127.0.0.1:8085/work-flow-task/report-apply   #审批系统接口funccode


bid-end:
  url:

#常量
app:
  constant:
    #工作流bpmn文件保存地址
    bpmn-save-path: /activiti/bpmn/
    #excel、word模板文件存储绝对路径
    mould-save-path: /home/zdrcsvc/service/mould
    #文件存储绝对路径
    file-save-path: /home/zdrcsvc/service/file
